server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&db_daily_management&serverTimezone=GMT&useSSL=false
      username: root
      password: xzh520
mybatis-plus:
  type-aliases-package: com.xue.springclou.entities
  mapper-locations: classpath*:/mapper/*.xml